%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/apr7_px4flow_kalman/succcessful_position_hold/flight1.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/04/29 13:51:49
clear all
close all
%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/apr7_px4flow_kalman/succcessful_position_hold/flight1.csv';
delimiter = ',';
startRow = 2;
endRow = 922;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
c1 = dataArray{:, 1};
c2 = dataArray{:, 2};
c3 = dataArray{:, 3};
c4 = dataArray{:, 4};
c5 = dataArray{:, 5};
c6 = dataArray{:, 6};
c7 = dataArray{:, 7};
c8 = dataArray{:, 8};
c9 = dataArray{:, 9};
c10 = dataArray{:, 10};
c11 = dataArray{:, 11};
c12 = dataArray{:, 12};
c13 = dataArray{:, 13};
c14 = dataArray{:, 14};
c15 = dataArray{:, 15};
c16 = dataArray{:, 16};
c17 = dataArray{:, 17};
c18 = dataArray{:, 18};
c19 = dataArray{:, 19};
c20 = dataArray{:, 20};
c21 = dataArray{:, 21};
c22 = dataArray{:, 22};
c23 = dataArray{:, 23};
c24 = dataArray{:, 24};
c25 = dataArray{:, 25};
c26 = dataArray{:, 26};
c27 = dataArray{:, 27};
c28 = dataArray{:, 28};
c29 = dataArray{:, 29};
c30 = dataArray{:, 30};
c31 = dataArray{:, 31};
c32 = dataArray{:, 32};
c33 = dataArray{:, 33};
c34 = dataArray{:, 34};
c35 = dataArray{:, 35};
c36 = dataArray{:, 36};
time = c1/1000;
roll = c2/1000;
pitch = -c3/1000;
ax = c4/1000*9.81;
ay = c5/1000*9.81;
az = c6/1000*9.81;
gx = c7/1000; 
gy = -c8/1000;
gz = -c9/1000;
sgx = c10/1000*180/pi;
sgy = c11/1000*180/pi;
sgz = c12/1000*180/pi;
sroll = c13/1000*180/pi;
spitch = c14/1000*180/pi;
radio_3 = c15;
m1 = c21;
m2 = c22;
m3 = c23;
m4 = c24;
vx = c32/1000;
vy = c33/1000;
svz = c19/1000;
vz = c18/1000;


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;