
#include "nuitka/prelude.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_str_empty;
PyObject *const_dict_empty;
PyObject *const_float_0_25;
PyObject *const_int_pos_10;
PyObject *const_int_pos_16;
PyObject *const_int_pos_17;
PyObject *const_int_pos_32;
PyObject *const_int_pos_50;
PyObject *const_int_pos_64;
PyObject *const_int_pos_75;
PyObject *const_str_chr_42;
PyObject *const_int_pos_110;
PyObject *const_int_pos_128;
PyObject *const_int_pos_134;
PyObject *const_int_pos_150;
PyObject *const_int_pos_200;
PyObject *const_int_pos_256;
PyObject *const_int_pos_300;
PyObject *const_int_pos_600;
PyObject *const_str_plain__;
PyObject *const_str_plain_d;
PyObject *const_str_plain_e;
PyObject *const_str_plain_i;
PyObject *const_str_plain_n;
PyObject *const_str_plain_s;
PyObject *const_str_plain_x;
PyObject *const_tuple_empty;
PyObject *const_int_pos_1000;
PyObject *const_int_pos_1200;
PyObject *const_int_pos_1800;
PyObject *const_int_pos_2400;
PyObject *const_int_pos_4096;
PyObject *const_int_pos_4800;
PyObject *const_int_pos_9600;
PyObject *const_str_plain_cd;
PyObject *const_str_plain_fd;
PyObject *const_str_plain_os;
PyObject *const_str_plain_ri;
PyObject *const_int_pos_19200;
PyObject *const_int_pos_38400;
PyObject *const_int_pos_57600;
PyObject *const_str_plain_DCB;
PyObject *const_str_plain_Odd;
PyObject *const_str_plain_XON;
PyObject *const_str_plain_buf;
PyObject *const_str_plain_cts;
PyObject *const_str_plain_dsr;
PyObject *const_str_plain_err;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_max;
PyObject *const_str_plain_msg;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_int_pos_115200;
PyObject *const_str_plain_Even;
PyObject *const_str_plain_Mark;
PyObject *const_str_plain_None;
PyObject *const_str_plain_XOFF;
PyObject *const_str_plain_args;
PyObject *const_str_plain_data;
PyObject *const_str_plain_fInX;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_long;
PyObject *const_str_plain_name;
PyObject *const_str_plain_open;
PyObject *const_str_plain_port;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_self;
PyObject *const_str_plain_site;
PyObject *const_str_plain_size;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_DWORD;
PyObject *const_str_plain_Space;
PyObject *const_str_plain__port;
PyObject *const_str_plain_array;
PyObject *const_str_plain_close;
PyObject *const_str_plain_fNull;
PyObject *const_str_plain_fOutX;
PyObject *const_str_plain_flush;
PyObject *const_str_plain_level;
PyObject *const_str_plain_linux;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_ports;
PyObject *const_str_plain_range;
PyObject *const_str_plain_sleep;
PyObject *const_str_plain_split;
PyObject *const_str_plain_value;
PyObject *const_str_plain_win32;
PyObject *const_str_plain_write;
PyObject *const_str_plain_CLRDTR;
PyObject *const_str_plain_CLRRTS;
PyObject *const_str_plain_EV_ERR;
PyObject *const_str_plain_Parity;
PyObject *const_str_plain_SETDTR;
PyObject *const_str_plain_SETRTS;
PyObject *const_str_plain_SETXON;
PyObject *const_str_plain_Serial;
PyObject *const_str_plain_append;
PyObject *const_str_plain_ctypes;
PyObject *const_str_plain_cygwin;
PyObject *const_str_plain_darwin;
PyObject *const_str_plain_enable;
PyObject *const_str_plain_format;
PyObject *const_str_plain_hEvent;
PyObject *const_str_plain_kd_yaw;
PyObject *const_str_plain_ki_yaw;
PyObject *const_str_plain_kp_yaw;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_params;
PyObject *const_str_plain_serial;
PyObject *const_str_plain_setDTR;
PyObject *const_str_plain_setRTS;
PyObject *const_str_plain_setter;
PyObject *const_str_plain_xrange;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_plain_COMSTAT;
PyObject *const_str_plain_SETXOFF;
PyObject *const_str_plain_SIXBITS;
PyObject *const_str_plain_Timeout;
PyObject *const_str_plain_XonChar;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain__dsrdtr;
PyObject *const_str_plain__parity;
PyObject *const_str_plain__rtscts;
PyObject *const_str_plain_cbInQue;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_expired;
PyObject *const_str_plain_fBinary;
PyObject *const_str_plain_fParity;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_is_open;
PyObject *const_str_plain_kd_roll;
PyObject *const_str_plain_ki_roll;
PyObject *const_str_plain_kp_roll;
PyObject *const_str_plain_portstr;
PyObject *const_str_plain_timeout;
PyObject *const_int_pos_1073741824;
PyObject *const_str_plain_BaudRate;
PyObject *const_str_plain_ByteSize;
PyObject *const_str_plain_FIVEBITS;
PyObject *const_str_plain_MAXDWORD;
PyObject *const_str_plain_NOPARITY;
PyObject *const_str_plain_ReadFile;
PyObject *const_str_plain_StopBits;
PyObject *const_str_plain_XoffChar;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain__timeout;
PyObject *const_str_plain__xonxoff;
PyObject *const_str_plain_baudrate;
PyObject *const_str_plain_cbOutQue;
PyObject *const_str_plain_duration;
PyObject *const_str_plain_exc_type;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_kd_pitch;
PyObject *const_str_plain_ki_pitch;
PyObject *const_str_plain_kp_pitch;
PyObject *const_str_plain_loopback;
PyObject *const_str_plain_platform;
PyObject *const_str_plain_to_bytes;
PyObject *const_str_plain_BAUDRATES;
PyObject *const_str_plain_EIGHTBITS;
PyObject *const_str_plain_MS_CTS_ON;
PyObject *const_str_plain_MS_DSR_ON;
PyObject *const_str_plain_ODDPARITY;
PyObject *const_str_plain_PurgeComm;
PyObject *const_str_plain_SEVENBITS;
PyObject *const_str_plain_SetupComm;
PyObject *const_str_plain_WriteFile;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain__baudrate;
PyObject *const_str_plain__bytesize;
PyObject *const_str_plain__stopbits;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_exc_value;
PyObject *const_str_plain_exclusive;
PyObject *const_str_plain_sendBreak;
PyObject *const_str_plain_time_left;
PyObject *const_tuple_str_dot_tuple;
PyObject *const_str_plain_CancelIoEx;
PyObject *const_str_plain_CreateFile;
PyObject *const_str_plain_EVENPARITY;
PyObject *const_str_plain_MARKPARITY;
PyObject *const_str_plain_MS_RING_ON;
PyObject *const_str_plain_MS_RLSD_ON;
PyObject *const_str_plain_ONESTOPBIT;
PyObject *const_str_plain_OVERLAPPED;
PyObject *const_str_plain_PARITY_ODD;
PyObject *const_str_plain_ResetEvent;
PyObject *const_str_plain_SerialBase;
PyObject *const_str_plain_SerialPort;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain__dtr_state;
PyObject *const_str_plain__exclusive;
PyObject *const_str_plain__rts_state;
PyObject *const_str_plain_fErrorChar;
PyObject *const_str_plain_in_waiting;
PyObject *const_str_plain_send_break;
PyObject *const_str_plain_startswith;
PyObject *const_str_plain_CloseHandle;
PyObject *const_str_plain_CreateEvent;
PyObject *const_str_plain_PARITY_EVEN;
PyObject *const_str_plain_PARITY_MARK;
PyObject *const_str_plain_PARITY_NONE;
PyObject *const_str_plain_SPACEPARITY;
PyObject *const_str_plain_SetCommMask;
PyObject *const_str_plain_TWOSTOPBITS;
PyObject *const_str_plain_VTIMESerial;
PyObject *const_str_plain___delattr__;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___setattr__;
PyObject *const_str_plain__rs485_mode;
PyObject *const_str_plain_active_port;
PyObject *const_str_plain_cancel_read;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_fDtrControl;
PyObject *const_str_plain_fRtsControl;
PyObject *const_str_plain_is_infinite;
PyObject *const_str_plain_out_waiting;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_str_plain_COMMTIMEOUTS;
PyObject *const_str_plain_GENERIC_READ;
PyObject *const_str_plain_GetCommState;
PyObject *const_str_plain_GetLastError;
PyObject *const_str_plain_ONE5STOPBITS;
PyObject *const_str_plain_PARITY_SPACE;
PyObject *const_str_plain_STOPBITS_ONE;
PyObject *const_str_plain_STOPBITS_TWO;
PyObject *const_str_plain_SetCommBreak;
PyObject *const_str_plain_SetCommState;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain__break_state;
PyObject *const_str_plain__port_handle;
PyObject *const_str_plain_cancel_write;
PyObject *const_str_plain_fOutxCtsFlow;
PyObject *const_str_plain_fOutxDsrFlow;
PyObject *const_str_plain_serial_ports;
PyObject *const_str_plain_staticmethod;
PyObject *const_tuple_float_0_25_tuple;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_str_plain_ERROR_SUCCESS;
PyObject *const_str_plain_GENERIC_WRITE;
PyObject *const_str_plain_OPEN_EXISTING;
PyObject *const_str_plain_PURGE_RXABORT;
PyObject *const_str_plain_PURGE_RXCLEAR;
PyObject *const_str_plain_PURGE_TXABORT;
PyObject *const_str_plain_PURGE_TXCLEAR;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain_exc_traceback;
PyObject *const_str_plain_fAbortOnError;
PyObject *const_str_plain_transmit_Data;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_ClearCommBreak;
PyObject *const_str_plain_ClearCommError;
PyObject *const_str_plain__write_timeout;
PyObject *const_str_plain_rs485_settings;
PyObject *const_str_plain_GetCommTimeouts;
PyObject *const_str_plain_PosixPollSerial;
PyObject *const_str_plain_SerialException;
PyObject *const_str_plain_SetCommTimeouts;
PyObject *const_str_plain_delay_before_rx;
PyObject *const_str_plain_delay_before_tx;
PyObject *const_str_plain_is_non_blocking;
PyObject *const_str_plain_ERROR_IO_PENDING;
PyObject *const_str_plain_portNotOpenError;
PyObject *const_str_plain_rts_level_for_rx;
PyObject *const_str_plain_rts_level_for_tx;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain__reconfigure_port;
PyObject *const_str_plain__update_dtr_state;
PyObject *const_str_plain__update_rts_state;
PyObject *const_str_plain_writeTimeoutError;
PyObject *const_str_plain_DTR_CONTROL_ENABLE;
PyObject *const_str_plain_EscapeCommFunction;
PyObject *const_str_plain_GetCommModemStatus;
PyObject *const_str_plain_RTS_CONTROL_ENABLE;
PyObject *const_str_plain_RTS_CONTROL_TOGGLE;
PyObject *const_str_plain_reset_input_buffer;
PyObject *const_str_plain_serialportsExample;
PyObject *const_str_plain_DTR_CONTROL_DISABLE;
PyObject *const_str_plain_ERROR_IO_INCOMPLETE;
PyObject *const_str_plain_GetOverlappedResult;
PyObject *const_str_plain_RTS_CONTROL_DISABLE;
PyObject *const_str_plain_ReadIntervalTimeout;
PyObject *const_str_plain__inter_byte_timeout;
PyObject *const_str_plain__update_break_state;
PyObject *const_str_plain_reset_output_buffer;
PyObject *const_str_plain_FILE_FLAG_OVERLAPPED;
PyObject *const_str_plain_INVALID_HANDLE_VALUE;
PyObject *const_str_plain_DTR_CONTROL_HANDSHAKE;
PyObject *const_str_plain_FILE_ATTRIBUTE_NORMAL;
PyObject *const_str_plain_RTS_CONTROL_HANDSHAKE;
PyObject *const_str_plain_serial_Object_handling;
PyObject *const_str_plain_ERROR_NOT_ENOUGH_MEMORY;
PyObject *const_str_plain_ERROR_OPERATION_ABORTED;
PyObject *const_str_plain_STOPBITS_ONE_POINT_FIVE;
PyObject *const_str_plain_set_output_flow_control;
PyObject *const_str_plain_ReadTotalTimeoutConstant;
PyObject *const_str_plain_ERROR_INVALID_USER_BUFFER;
PyObject *const_str_plain_WriteTotalTimeoutConstant;
PyObject *const_tuple_str_plain_self_str_plain_key_tuple;
PyObject *const_tuple_str_plain_self_str_plain_data_tuple;
PyObject *const_tuple_str_plain_self_str_plain_port_tuple;
PyObject *const_bytearray_72cdf64f605ef12d57287fc4b61c2b5e;
PyObject *const_str_digest_06425a8e1b9d5eab562978eb6eacf777;
PyObject *const_str_digest_07b1711e38859082a6702459b5aea4e1;
PyObject *const_str_digest_088e326eed737fbd2d5feedf060c96ff;
PyObject *const_str_digest_09388aafcb6adb40da642c8223c8e7c5;
PyObject *const_str_digest_094a5755decb0ff88251d419e9b9deb6;
PyObject *const_str_digest_145bf772d86c3cb38f291d317430df01;
PyObject *const_str_digest_14aa7bed476b499178dd8a4fa54d666e;
PyObject *const_str_digest_1d3403f47e70d0d3c7366e99c0db7fa8;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_2b96e25c8d393fdf065d358454fdf25c;
PyObject *const_str_digest_33be1aa9452ea1a35db7fc513fc42137;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_464621b44ad0d4884db68a925fcb5c8f;
PyObject *const_str_digest_47be6feae340d11ceea1b2be1116c946;
PyObject *const_str_digest_4b91cca6339a9a892cf0e30d6bd1bdfc;
PyObject *const_str_digest_54cde0cd7a92974ff918f0defbd1eeb9;
PyObject *const_str_digest_57027c3185c735e629ff3e28a5a985c8;
PyObject *const_str_digest_58961c73026e70b23b08cf381b49e04e;
PyObject *const_str_digest_59d8c08c8b321dd488f0cfd9cc30b9cf;
PyObject *const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1;
PyObject *const_str_digest_66c5c36b8185e52d7e7b19bd4f1801a9;
PyObject *const_str_digest_67381b97568fd04864d7225afb09d3b9;
PyObject *const_str_digest_67e30ad9cc029aa9b34457de3a368897;
PyObject *const_str_digest_72db89f2656c7536ad3ca9676d132571;
PyObject *const_str_digest_754a48779fa33a021f9b94595a1c7603;
PyObject *const_str_digest_7bb187c562694df4ba2daaaf74308c83;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_9ba51f6bdeff944f83e458f9b58790b4;
PyObject *const_str_digest_a41f7446b10852b7fa7917c8946aa5e1;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_bd2e98b142ff21c9f389c674d6946c9a;
PyObject *const_str_digest_c987d57c872daa303d57e57028663dbb;
PyObject *const_str_digest_ca3087f1fed5e9b894c48e0dbbd2f218;
PyObject *const_str_digest_ca5d450d1c32d53f6bfc010c234e26bd;
PyObject *const_str_digest_cee0e65b93fa2a88bd408284fcdf4582;
PyObject *const_str_digest_faa07c45c026cd5370bf39ce65b9f2d8;
PyObject *const_tuple_str_plain_self_str_plain_enable_tuple;
PyObject *const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple;
PyObject *const_tuple_str_plain_self_str_plain_duration_tuple;
PyObject *const_tuple_str_plain_self_str_plain_exclusive_tuple;
PyObject *const_tuple_str_plain_self_str_plain_rs485_settings_tuple;
PyObject *const_tuple_str_digest_088e326eed737fbd2d5feedf060c96ff_tuple;
PyObject *const_tuple_str_digest_145bf772d86c3cb38f291d317430df01_tuple;
PyObject *const_tuple_str_digest_a41f7446b10852b7fa7917c8946aa5e1_tuple;
PyObject *const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyInt_FromLong( 0l );
    const_str_dot = UNSTREAM_CHAR( 46, 0 );
    const_int_neg_1 = PyInt_FromLong( -1l );
    const_int_pos_1 = PyInt_FromLong( 1l );
    const_int_pos_2 = PyInt_FromLong( 2l );
    const_int_pos_3 = PyInt_FromLong( 3l );
    const_int_pos_4 = PyInt_FromLong( 4l );
    const_int_pos_5 = PyInt_FromLong( 5l );
    const_int_pos_6 = PyInt_FromLong( 6l );
    const_int_pos_7 = PyInt_FromLong( 7l );
    const_int_pos_8 = PyInt_FromLong( 8l );
    const_str_empty = UNSTREAM_STRING( &constant_bin[ 0 ], 0, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_float_0_25 = UNSTREAM_FLOAT( &constant_bin[ 17223 ] );
    const_int_pos_10 = PyInt_FromLong( 10l );
    const_int_pos_16 = PyInt_FromLong( 16l );
    const_int_pos_17 = PyInt_FromLong( 17l );
    const_int_pos_32 = PyInt_FromLong( 32l );
    const_int_pos_50 = PyInt_FromLong( 50l );
    const_int_pos_64 = PyInt_FromLong( 64l );
    const_int_pos_75 = PyInt_FromLong( 75l );
    const_str_chr_42 = UNSTREAM_CHAR( 42, 0 );
    const_int_pos_110 = PyInt_FromLong( 110l );
    const_int_pos_128 = PyInt_FromLong( 128l );
    const_int_pos_134 = PyInt_FromLong( 134l );
    const_int_pos_150 = PyInt_FromLong( 150l );
    const_int_pos_200 = PyInt_FromLong( 200l );
    const_int_pos_256 = PyInt_FromLong( 256l );
    const_int_pos_300 = PyInt_FromLong( 300l );
    const_int_pos_600 = PyInt_FromLong( 600l );
    const_str_plain__ = UNSTREAM_CHAR( 95, 1 );
    const_str_plain_d = UNSTREAM_CHAR( 100, 1 );
    const_str_plain_e = UNSTREAM_CHAR( 101, 1 );
    const_str_plain_i = UNSTREAM_CHAR( 105, 1 );
    const_str_plain_n = UNSTREAM_CHAR( 110, 1 );
    const_str_plain_s = UNSTREAM_CHAR( 115, 1 );
    const_str_plain_x = UNSTREAM_CHAR( 120, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_int_pos_1000 = PyInt_FromLong( 1000l );
    const_int_pos_1200 = PyInt_FromLong( 1200l );
    const_int_pos_1800 = PyInt_FromLong( 1800l );
    const_int_pos_2400 = PyInt_FromLong( 2400l );
    const_int_pos_4096 = PyInt_FromLong( 4096l );
    const_int_pos_4800 = PyInt_FromLong( 4800l );
    const_int_pos_9600 = PyInt_FromLong( 9600l );
    const_str_plain_cd = UNSTREAM_STRING( &constant_bin[ 3844 ], 2, 1 );
    const_str_plain_fd = UNSTREAM_STRING( &constant_bin[ 17231 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING( &constant_bin[ 752 ], 2, 1 );
    const_str_plain_ri = UNSTREAM_STRING( &constant_bin[ 130 ], 2, 1 );
    const_int_pos_19200 = PyInt_FromLong( 19200l );
    const_int_pos_38400 = PyInt_FromLong( 38400l );
    const_int_pos_57600 = PyInt_FromLong( 57600l );
    const_str_plain_DCB = UNSTREAM_STRING( &constant_bin[ 14334 ], 3, 1 );
    const_str_plain_Odd = UNSTREAM_STRING( &constant_bin[ 17233 ], 3, 1 );
    const_str_plain_XON = UNSTREAM_STRING( &constant_bin[ 2979 ], 3, 1 );
    const_str_plain_buf = UNSTREAM_STRING( &constant_bin[ 3670 ], 3, 1 );
    const_str_plain_cts = UNSTREAM_STRING( &constant_bin[ 7506 ], 3, 1 );
    const_str_plain_dsr = UNSTREAM_STRING( &constant_bin[ 7514 ], 3, 1 );
    const_str_plain_err = UNSTREAM_STRING( &constant_bin[ 3763 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING( &constant_bin[ 444 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING( &constant_bin[ 951 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING( &constant_bin[ 4426 ], 3, 1 );
    const_str_plain_max = UNSTREAM_STRING( &constant_bin[ 17236 ], 3, 1 );
    const_str_plain_msg = UNSTREAM_STRING( &constant_bin[ 17239 ], 3, 1 );
    const_str_plain_pop = UNSTREAM_STRING( &constant_bin[ 17242 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING( &constant_bin[ 17245 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING( &constant_bin[ 3597 ], 3, 1 );
    const_int_pos_115200 = PyInt_FromLong( 115200l );
    const_str_plain_Even = UNSTREAM_STRING( &constant_bin[ 15121 ], 4, 1 );
    const_str_plain_Mark = UNSTREAM_STRING( &constant_bin[ 17248 ], 4, 1 );
    const_str_plain_None = UNSTREAM_STRING( &constant_bin[ 9176 ], 4, 1 );
    const_str_plain_XOFF = UNSTREAM_STRING( &constant_bin[ 2982 ], 4, 1 );
    const_str_plain_args = UNSTREAM_STRING( &constant_bin[ 17252 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING( &constant_bin[ 15 ], 4, 1 );
    const_str_plain_fInX = UNSTREAM_STRING( &constant_bin[ 17256 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING( &constant_bin[ 11101 ], 4, 1 );
    const_str_plain_keys = UNSTREAM_STRING( &constant_bin[ 10452 ], 4, 1 );
    const_str_plain_long = UNSTREAM_STRING( &constant_bin[ 16405 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING( &constant_bin[ 708 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING( &constant_bin[ 628 ], 4, 1 );
    const_str_plain_port = UNSTREAM_STRING( &constant_bin[ 173 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING( &constant_bin[ 363 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING( &constant_bin[ 8496 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING( &constant_bin[ 17260 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING( &constant_bin[ 665 ], 4, 1 );
    const_str_plain_size = UNSTREAM_STRING( &constant_bin[ 2322 ], 4, 1 );
    const_str_plain_time = UNSTREAM_STRING( &constant_bin[ 3776 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING( &constant_bin[ 416 ], 4, 1 );
    const_str_plain_DWORD = UNSTREAM_STRING( &constant_bin[ 14709 ], 5, 1 );
    const_str_plain_Space = UNSTREAM_STRING( &constant_bin[ 17264 ], 5, 1 );
    const_str_plain__port = UNSTREAM_STRING( &constant_bin[ 607 ], 5, 1 );
    const_str_plain_array = UNSTREAM_STRING( &constant_bin[ 1741 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING( &constant_bin[ 7289 ], 5, 1 );
    const_str_plain_fNull = UNSTREAM_STRING( &constant_bin[ 17269 ], 5, 1 );
    const_str_plain_fOutX = UNSTREAM_STRING( &constant_bin[ 17274 ], 5, 1 );
    const_str_plain_flush = UNSTREAM_STRING( &constant_bin[ 6082 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING( &constant_bin[ 14246 ], 5, 1 );
    const_str_plain_linux = UNSTREAM_STRING( &constant_bin[ 17279 ], 5, 1 );
    const_str_plain_lower = UNSTREAM_STRING( &constant_bin[ 1578 ], 5, 1 );
    const_str_plain_ports = UNSTREAM_STRING( &constant_bin[ 608 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING( &constant_bin[ 17284 ], 5, 1 );
    const_str_plain_sleep = UNSTREAM_STRING( &constant_bin[ 17289 ], 5, 1 );
    const_str_plain_split = UNSTREAM_STRING( &constant_bin[ 17294 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING( &constant_bin[ 9715 ], 5, 1 );
    const_str_plain_win32 = UNSTREAM_STRING( &constant_bin[ 12547 ], 5, 1 );
    const_str_plain_write = UNSTREAM_STRING( &constant_bin[ 129 ], 5, 1 );
    const_str_plain_CLRDTR = UNSTREAM_STRING( &constant_bin[ 17299 ], 6, 1 );
    const_str_plain_CLRRTS = UNSTREAM_STRING( &constant_bin[ 17305 ], 6, 1 );
    const_str_plain_EV_ERR = UNSTREAM_STRING( &constant_bin[ 16096 ], 6, 1 );
    const_str_plain_Parity = UNSTREAM_STRING( &constant_bin[ 17311 ], 6, 1 );
    const_str_plain_SETDTR = UNSTREAM_STRING( &constant_bin[ 17317 ], 6, 1 );
    const_str_plain_SETRTS = UNSTREAM_STRING( &constant_bin[ 17323 ], 6, 1 );
    const_str_plain_SETXON = UNSTREAM_STRING( &constant_bin[ 14936 ], 6, 1 );
    const_str_plain_Serial = UNSTREAM_STRING( &constant_bin[ 878 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING( &constant_bin[ 1386 ], 6, 1 );
    const_str_plain_ctypes = UNSTREAM_STRING( &constant_bin[ 14117 ], 6, 1 );
    const_str_plain_cygwin = UNSTREAM_STRING( &constant_bin[ 17329 ], 6, 1 );
    const_str_plain_darwin = UNSTREAM_STRING( &constant_bin[ 17335 ], 6, 1 );
    const_str_plain_enable = UNSTREAM_STRING( &constant_bin[ 3129 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING( &constant_bin[ 17341 ], 6, 1 );
    const_str_plain_hEvent = UNSTREAM_STRING( &constant_bin[ 17347 ], 6, 1 );
    const_str_plain_kd_yaw = UNSTREAM_STRING( &constant_bin[ 17353 ], 6, 1 );
    const_str_plain_ki_yaw = UNSTREAM_STRING( &constant_bin[ 17359 ], 6, 1 );
    const_str_plain_kp_yaw = UNSTREAM_STRING( &constant_bin[ 17365 ], 6, 1 );
    const_str_plain_kwargs = UNSTREAM_STRING( &constant_bin[ 17371 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING( &constant_bin[ 17377 ], 6, 1 );
    const_str_plain_params = UNSTREAM_STRING( &constant_bin[ 17383 ], 6, 1 );
    const_str_plain_serial = UNSTREAM_STRING( &constant_bin[ 679 ], 6, 1 );
    const_str_plain_setDTR = UNSTREAM_STRING( &constant_bin[ 8671 ], 6, 1 );
    const_str_plain_setRTS = UNSTREAM_STRING( &constant_bin[ 8660 ], 6, 1 );
    const_str_plain_setter = UNSTREAM_STRING( &constant_bin[ 17389 ], 6, 1 );
    const_str_plain_xrange = UNSTREAM_STRING( &constant_bin[ 17283 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_tuple_true_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_true_tuple, 0, Py_True ); Py_INCREF( Py_True );
    const_str_plain_COMSTAT = UNSTREAM_STRING( &constant_bin[ 14540 ], 7, 1 );
    const_str_plain_SETXOFF = UNSTREAM_STRING( &constant_bin[ 15036 ], 7, 1 );
    const_str_plain_SIXBITS = UNSTREAM_STRING( &constant_bin[ 17395 ], 7, 1 );
    const_str_plain_Timeout = UNSTREAM_STRING( &constant_bin[ 1816 ], 7, 1 );
    const_str_plain_XonChar = UNSTREAM_STRING( &constant_bin[ 17402 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING( &constant_bin[ 17409 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING( &constant_bin[ 17416 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING( &constant_bin[ 7246 ], 7, 1 );
    const_str_plain__dsrdtr = UNSTREAM_STRING( &constant_bin[ 17423 ], 7, 1 );
    const_str_plain__parity = UNSTREAM_STRING( &constant_bin[ 17430 ], 7, 1 );
    const_str_plain__rtscts = UNSTREAM_STRING( &constant_bin[ 17437 ], 7, 1 );
    const_str_plain_cbInQue = UNSTREAM_STRING( &constant_bin[ 17444 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING( &constant_bin[ 17451 ], 7, 1 );
    const_str_plain_expired = UNSTREAM_STRING( &constant_bin[ 8911 ], 7, 1 );
    const_str_plain_fBinary = UNSTREAM_STRING( &constant_bin[ 17458 ], 7, 1 );
    const_str_plain_fParity = UNSTREAM_STRING( &constant_bin[ 17465 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING( &constant_bin[ 17472 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING( &constant_bin[ 17479 ], 7, 1 );
    const_str_plain_is_open = UNSTREAM_STRING( &constant_bin[ 9847 ], 7, 1 );
    const_str_plain_kd_roll = UNSTREAM_STRING( &constant_bin[ 17486 ], 7, 1 );
    const_str_plain_ki_roll = UNSTREAM_STRING( &constant_bin[ 17493 ], 7, 1 );
    const_str_plain_kp_roll = UNSTREAM_STRING( &constant_bin[ 17500 ], 7, 1 );
    const_str_plain_portstr = UNSTREAM_STRING( &constant_bin[ 9865 ], 7, 1 );
    const_str_plain_timeout = UNSTREAM_STRING( &constant_bin[ 4932 ], 7, 1 );
    const_int_pos_1073741824 = PyInt_FromLong( 1073741824l );
    const_str_plain_BaudRate = UNSTREAM_STRING( &constant_bin[ 17507 ], 8, 1 );
    const_str_plain_ByteSize = UNSTREAM_STRING( &constant_bin[ 17515 ], 8, 1 );
    const_str_plain_FIVEBITS = UNSTREAM_STRING( &constant_bin[ 17523 ], 8, 1 );
    const_str_plain_MAXDWORD = UNSTREAM_STRING( &constant_bin[ 16014 ], 8, 1 );
    const_str_plain_NOPARITY = UNSTREAM_STRING( &constant_bin[ 16136 ], 8, 1 );
    const_str_plain_ReadFile = UNSTREAM_STRING( &constant_bin[ 14390 ], 8, 1 );
    const_str_plain_StopBits = UNSTREAM_STRING( &constant_bin[ 17531 ], 8, 1 );
    const_str_plain_XoffChar = UNSTREAM_STRING( &constant_bin[ 17539 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING( &constant_bin[ 17547 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING( &constant_bin[ 8573 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING( &constant_bin[ 17555 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING( &constant_bin[ 686 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING( &constant_bin[ 17563 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING( &constant_bin[ 17571 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING( &constant_bin[ 17579 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING( &constant_bin[ 17587 ], 8, 1 );
    const_str_plain__timeout = UNSTREAM_STRING( &constant_bin[ 8317 ], 8, 1 );
    const_str_plain__xonxoff = UNSTREAM_STRING( &constant_bin[ 17595 ], 8, 1 );
    const_str_plain_baudrate = UNSTREAM_STRING( &constant_bin[ 6329 ], 8, 1 );
    const_str_plain_cbOutQue = UNSTREAM_STRING( &constant_bin[ 17603 ], 8, 1 );
    const_str_plain_duration = UNSTREAM_STRING( &constant_bin[ 3418 ], 8, 1 );
    const_str_plain_exc_type = UNSTREAM_STRING( &constant_bin[ 17611 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING( &constant_bin[ 17619 ], 8, 1 );
    const_str_plain_kd_pitch = UNSTREAM_STRING( &constant_bin[ 17627 ], 8, 1 );
    const_str_plain_ki_pitch = UNSTREAM_STRING( &constant_bin[ 17635 ], 8, 1 );
    const_str_plain_kp_pitch = UNSTREAM_STRING( &constant_bin[ 17643 ], 8, 1 );
    const_str_plain_loopback = UNSTREAM_STRING( &constant_bin[ 14180 ], 8, 1 );
    const_str_plain_platform = UNSTREAM_STRING( &constant_bin[ 790 ], 8, 1 );
    const_str_plain_to_bytes = UNSTREAM_STRING( &constant_bin[ 17651 ], 8, 1 );
    const_str_plain_BAUDRATES = UNSTREAM_STRING( &constant_bin[ 8160 ], 9, 1 );
    const_str_plain_EIGHTBITS = UNSTREAM_STRING( &constant_bin[ 17659 ], 9, 1 );
    const_str_plain_MS_CTS_ON = UNSTREAM_STRING( &constant_bin[ 14821 ], 9, 1 );
    const_str_plain_MS_DSR_ON = UNSTREAM_STRING( &constant_bin[ 16027 ], 9, 1 );
    const_str_plain_ODDPARITY = UNSTREAM_STRING( &constant_bin[ 15418 ], 9, 1 );
    const_str_plain_PurgeComm = UNSTREAM_STRING( &constant_bin[ 14965 ], 9, 1 );
    const_str_plain_SEVENBITS = UNSTREAM_STRING( &constant_bin[ 17668 ], 9, 1 );
    const_str_plain_SetupComm = UNSTREAM_STRING( &constant_bin[ 15273 ], 9, 1 );
    const_str_plain_WriteFile = UNSTREAM_STRING( &constant_bin[ 13263 ], 9, 1 );
    const_str_plain___class__ = UNSTREAM_STRING( &constant_bin[ 17677 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING( &constant_bin[ 8559 ], 9, 1 );
    const_str_plain__baudrate = UNSTREAM_STRING( &constant_bin[ 6328 ], 9, 1 );
    const_str_plain__bytesize = UNSTREAM_STRING( &constant_bin[ 17686 ], 9, 1 );
    const_str_plain__stopbits = UNSTREAM_STRING( &constant_bin[ 17695 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING( &constant_bin[ 2938 ], 9, 1 );
    const_str_plain_exc_value = UNSTREAM_STRING( &constant_bin[ 17704 ], 9, 1 );
    const_str_plain_exclusive = UNSTREAM_STRING( &constant_bin[ 5548 ], 9, 1 );
    const_str_plain_sendBreak = UNSTREAM_STRING( &constant_bin[ 8646 ], 9, 1 );
    const_str_plain_time_left = UNSTREAM_STRING( &constant_bin[ 17713 ], 9, 1 );
    const_tuple_str_dot_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_dot_tuple, 0, const_str_dot ); Py_INCREF( const_str_dot );
    const_str_plain_CancelIoEx = UNSTREAM_STRING( &constant_bin[ 17722 ], 10, 1 );
    const_str_plain_CreateFile = UNSTREAM_STRING( &constant_bin[ 15935 ], 10, 1 );
    const_str_plain_EVENPARITY = UNSTREAM_STRING( &constant_bin[ 15512 ], 10, 1 );
    const_str_plain_MARKPARITY = UNSTREAM_STRING( &constant_bin[ 17732 ], 10, 1 );
    const_str_plain_MS_RING_ON = UNSTREAM_STRING( &constant_bin[ 16041 ], 10, 1 );
    const_str_plain_MS_RLSD_ON = UNSTREAM_STRING( &constant_bin[ 14897 ], 10, 1 );
    const_str_plain_ONESTOPBIT = UNSTREAM_STRING( &constant_bin[ 15021 ], 10, 1 );
    const_str_plain_OVERLAPPED = UNSTREAM_STRING( &constant_bin[ 14560 ], 10, 1 );
    const_str_plain_PARITY_ODD = UNSTREAM_STRING( &constant_bin[ 17742 ], 10, 1 );
    const_str_plain_ResetEvent = UNSTREAM_STRING( &constant_bin[ 15624 ], 10, 1 );
    const_str_plain_SerialBase = UNSTREAM_STRING( &constant_bin[ 17752 ], 10, 1 );
    const_str_plain_SerialPort = UNSTREAM_STRING( &constant_bin[ 3206 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING( &constant_bin[ 17762 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING( &constant_bin[ 7231 ], 10, 1 );
    const_str_plain__dtr_state = UNSTREAM_STRING( &constant_bin[ 7491 ], 10, 1 );
    const_str_plain__exclusive = UNSTREAM_STRING( &constant_bin[ 17772 ], 10, 1 );
    const_str_plain__rts_state = UNSTREAM_STRING( &constant_bin[ 7469 ], 10, 1 );
    const_str_plain_fErrorChar = UNSTREAM_STRING( &constant_bin[ 17782 ], 10, 1 );
    const_str_plain_in_waiting = UNSTREAM_STRING( &constant_bin[ 7299 ], 10, 1 );
    const_str_plain_send_break = UNSTREAM_STRING( &constant_bin[ 7423 ], 10, 1 );
    const_str_plain_startswith = UNSTREAM_STRING( &constant_bin[ 17792 ], 10, 1 );
    const_str_plain_CloseHandle = UNSTREAM_STRING( &constant_bin[ 16149 ], 11, 1 );
    const_str_plain_CreateEvent = UNSTREAM_STRING( &constant_bin[ 15115 ], 11, 1 );
    const_str_plain_PARITY_EVEN = UNSTREAM_STRING( &constant_bin[ 17802 ], 11, 1 );
    const_str_plain_PARITY_MARK = UNSTREAM_STRING( &constant_bin[ 17813 ], 11, 1 );
    const_str_plain_PARITY_NONE = UNSTREAM_STRING( &constant_bin[ 17824 ], 11, 1 );
    const_str_plain_SPACEPARITY = UNSTREAM_STRING( &constant_bin[ 17835 ], 11, 1 );
    const_str_plain_SetCommMask = UNSTREAM_STRING( &constant_bin[ 15877 ], 11, 1 );
    const_str_plain_TWOSTOPBITS = UNSTREAM_STRING( &constant_bin[ 15979 ], 11, 1 );
    const_str_plain_VTIMESerial = UNSTREAM_STRING( &constant_bin[ 17846 ], 11, 1 );
    const_str_plain___delattr__ = UNSTREAM_STRING( &constant_bin[ 17857 ], 11, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING( &constant_bin[ 17868 ], 11, 1 );
    const_str_plain___setattr__ = UNSTREAM_STRING( &constant_bin[ 17879 ], 11, 1 );
    const_str_plain__rs485_mode = UNSTREAM_STRING( &constant_bin[ 6353 ], 11, 1 );
    const_str_plain_active_port = UNSTREAM_STRING( &constant_bin[ 17890 ], 11, 1 );
    const_str_plain_cancel_read = UNSTREAM_STRING( &constant_bin[ 7323 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING( &constant_bin[ 17901 ], 11, 1 );
    const_str_plain_fDtrControl = UNSTREAM_STRING( &constant_bin[ 17912 ], 11, 1 );
    const_str_plain_fRtsControl = UNSTREAM_STRING( &constant_bin[ 17923 ], 11, 1 );
    const_str_plain_is_infinite = UNSTREAM_STRING( &constant_bin[ 11914 ], 11, 1 );
    const_str_plain_out_waiting = UNSTREAM_STRING( &constant_bin[ 7536 ], 11, 1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_str_plain_COMMTIMEOUTS = UNSTREAM_STRING( &constant_bin[ 14615 ], 12, 1 );
    const_str_plain_GENERIC_READ = UNSTREAM_STRING( &constant_bin[ 15730 ], 12, 1 );
    const_str_plain_GetCommState = UNSTREAM_STRING( &constant_bin[ 15066 ], 12, 1 );
    const_str_plain_GetLastError = UNSTREAM_STRING( &constant_bin[ 14804 ], 12, 1 );
    const_str_plain_ONE5STOPBITS = UNSTREAM_STRING( &constant_bin[ 17934 ], 12, 1 );
    const_str_plain_PARITY_SPACE = UNSTREAM_STRING( &constant_bin[ 17946 ], 12, 1 );
    const_str_plain_STOPBITS_ONE = UNSTREAM_STRING( &constant_bin[ 17958 ], 12, 1 );
    const_str_plain_STOPBITS_TWO = UNSTREAM_STRING( &constant_bin[ 17970 ], 12, 1 );
    const_str_plain_SetCommBreak = UNSTREAM_STRING( &constant_bin[ 15364 ], 12, 1 );
    const_str_plain_SetCommState = UNSTREAM_STRING( &constant_bin[ 15907 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING( &constant_bin[ 17982 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING( &constant_bin[ 17994 ], 12, 1 );
    const_str_plain__break_state = UNSTREAM_STRING( &constant_bin[ 3039 ], 12, 1 );
    const_str_plain__port_handle = UNSTREAM_STRING( &constant_bin[ 18006 ], 12, 1 );
    const_str_plain_cancel_write = UNSTREAM_STRING( &constant_bin[ 7339 ], 12, 1 );
    const_str_plain_fOutxCtsFlow = UNSTREAM_STRING( &constant_bin[ 18018 ], 12, 1 );
    const_str_plain_fOutxDsrFlow = UNSTREAM_STRING( &constant_bin[ 18030 ], 12, 1 );
    const_str_plain_serial_ports = UNSTREAM_STRING( &constant_bin[ 18042 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING( &constant_bin[ 18054 ], 12, 1 );
    const_tuple_float_0_25_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_float_0_25_tuple, 0, const_float_0_25 ); Py_INCREF( const_float_0_25 );
    const_tuple_str_chr_42_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_42_tuple, 0, const_str_chr_42 ); Py_INCREF( const_str_chr_42 );
    const_str_plain_ERROR_SUCCESS = UNSTREAM_STRING( &constant_bin[ 18066 ], 13, 1 );
    const_str_plain_GENERIC_WRITE = UNSTREAM_STRING( &constant_bin[ 15832 ], 13, 1 );
    const_str_plain_OPEN_EXISTING = UNSTREAM_STRING( &constant_bin[ 15211 ], 13, 1 );
    const_str_plain_PURGE_RXABORT = UNSTREAM_STRING( &constant_bin[ 15048 ], 13, 1 );
    const_str_plain_PURGE_RXCLEAR = UNSTREAM_STRING( &constant_bin[ 15814 ], 13, 1 );
    const_str_plain_PURGE_TXABORT = UNSTREAM_STRING( &constant_bin[ 14947 ], 13, 1 );
    const_str_plain_PURGE_TXCLEAR = UNSTREAM_STRING( &constant_bin[ 15481 ], 13, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING( &constant_bin[ 18079 ], 13, 1 );
    const_str_plain_exc_traceback = UNSTREAM_STRING( &constant_bin[ 18092 ], 13, 1 );
    const_str_plain_fAbortOnError = UNSTREAM_STRING( &constant_bin[ 18105 ], 13, 1 );
    const_str_plain_transmit_Data = UNSTREAM_STRING( &constant_bin[ 18118 ], 13, 1 );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain_ClearCommBreak = UNSTREAM_STRING( &constant_bin[ 15319 ], 14, 1 );
    const_str_plain_ClearCommError = UNSTREAM_STRING( &constant_bin[ 13286 ], 14, 1 );
    const_str_plain__write_timeout = UNSTREAM_STRING( &constant_bin[ 18131 ], 14, 1 );
    const_str_plain_rs485_settings = UNSTREAM_STRING( &constant_bin[ 18145 ], 14, 1 );
    const_str_plain_GetCommTimeouts = UNSTREAM_STRING( &constant_bin[ 15604 ], 15, 1 );
    const_str_plain_PosixPollSerial = UNSTREAM_STRING( &constant_bin[ 18159 ], 15, 1 );
    const_str_plain_SerialException = UNSTREAM_STRING( &constant_bin[ 5737 ], 15, 1 );
    const_str_plain_SetCommTimeouts = UNSTREAM_STRING( &constant_bin[ 15381 ], 15, 1 );
    const_str_plain_delay_before_rx = UNSTREAM_STRING( &constant_bin[ 14047 ], 15, 1 );
    const_str_plain_delay_before_tx = UNSTREAM_STRING( &constant_bin[ 13990 ], 15, 1 );
    const_str_plain_is_non_blocking = UNSTREAM_STRING( &constant_bin[ 11894 ], 15, 1 );
    const_str_plain_ERROR_IO_PENDING = UNSTREAM_STRING( &constant_bin[ 15686 ], 16, 1 );
    const_str_plain_portNotOpenError = UNSTREAM_STRING( &constant_bin[ 18174 ], 16, 1 );
    const_str_plain_rts_level_for_rx = UNSTREAM_STRING( &constant_bin[ 14242 ], 16, 1 );
    const_str_plain_rts_level_for_tx = UNSTREAM_STRING( &constant_bin[ 14485 ], 16, 1 );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain__reconfigure_port = UNSTREAM_STRING( &constant_bin[ 7267 ], 17, 1 );
    const_str_plain__update_dtr_state = UNSTREAM_STRING( &constant_bin[ 7484 ], 17, 1 );
    const_str_plain__update_rts_state = UNSTREAM_STRING( &constant_bin[ 7462 ], 17, 1 );
    const_str_plain_writeTimeoutError = UNSTREAM_STRING( &constant_bin[ 18190 ], 17, 1 );
    const_str_plain_DTR_CONTROL_ENABLE = UNSTREAM_STRING( &constant_bin[ 14861 ], 18, 1 );
    const_str_plain_EscapeCommFunction = UNSTREAM_STRING( &constant_bin[ 15707 ], 18, 1 );
    const_str_plain_GetCommModemStatus = UNSTREAM_STRING( &constant_bin[ 12831 ], 18, 1 );
    const_str_plain_RTS_CONTROL_ENABLE = UNSTREAM_STRING( &constant_bin[ 15083 ], 18, 1 );
    const_str_plain_RTS_CONTROL_TOGGLE = UNSTREAM_STRING( &constant_bin[ 18207 ], 18, 1 );
    const_str_plain_reset_input_buffer = UNSTREAM_STRING( &constant_bin[ 7376 ], 18, 1 );
    const_str_plain_serialportsExample = UNSTREAM_STRING( &constant_bin[ 17202 ], 18, 1 );
    const_str_plain_DTR_CONTROL_DISABLE = UNSTREAM_STRING( &constant_bin[ 18225 ], 19, 1 );
    const_str_plain_ERROR_IO_INCOMPLETE = UNSTREAM_STRING( &constant_bin[ 18244 ], 19, 1 );
    const_str_plain_GetOverlappedResult = UNSTREAM_STRING( &constant_bin[ 13016 ], 19, 1 );
    const_str_plain_RTS_CONTROL_DISABLE = UNSTREAM_STRING( &constant_bin[ 18263 ], 19, 1 );
    const_str_plain_ReadIntervalTimeout = UNSTREAM_STRING( &constant_bin[ 18282 ], 19, 1 );
    const_str_plain__inter_byte_timeout = UNSTREAM_STRING( &constant_bin[ 18301 ], 19, 1 );
    const_str_plain__update_break_state = UNSTREAM_STRING( &constant_bin[ 3032 ], 19, 1 );
    const_str_plain_reset_output_buffer = UNSTREAM_STRING( &constant_bin[ 7399 ], 19, 1 );
    const_str_plain_FILE_FLAG_OVERLAPPED = UNSTREAM_STRING( &constant_bin[ 15237 ], 20, 1 );
    const_str_plain_INVALID_HANDLE_VALUE = UNSTREAM_STRING( &constant_bin[ 18320 ], 20, 1 );
    const_str_plain_DTR_CONTROL_HANDSHAKE = UNSTREAM_STRING( &constant_bin[ 15788 ], 21, 1 );
    const_str_plain_FILE_ATTRIBUTE_NORMAL = UNSTREAM_STRING( &constant_bin[ 14835 ], 21, 1 );
    const_str_plain_RTS_CONTROL_HANDSHAKE = UNSTREAM_STRING( &constant_bin[ 15747 ], 21, 1 );
    const_str_plain_serial_Object_handling = UNSTREAM_STRING( &constant_bin[ 16765 ], 22, 1 );
    const_str_plain_ERROR_NOT_ENOUGH_MEMORY = UNSTREAM_STRING( &constant_bin[ 18340 ], 23, 1 );
    const_str_plain_ERROR_OPERATION_ABORTED = UNSTREAM_STRING( &constant_bin[ 18363 ], 23, 1 );
    const_str_plain_STOPBITS_ONE_POINT_FIVE = UNSTREAM_STRING( &constant_bin[ 18386 ], 23, 1 );
    const_str_plain_set_output_flow_control = UNSTREAM_STRING( &constant_bin[ 7590 ], 23, 1 );
    const_str_plain_ReadTotalTimeoutConstant = UNSTREAM_STRING( &constant_bin[ 18409 ], 24, 1 );
    const_str_plain_ERROR_INVALID_USER_BUFFER = UNSTREAM_STRING( &constant_bin[ 18433 ], 25, 1 );
    const_str_plain_WriteTotalTimeoutConstant = UNSTREAM_STRING( &constant_bin[ 18458 ], 25, 1 );
    const_tuple_str_plain_self_str_plain_key_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_key_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_key_tuple, 1, const_str_plain_key ); Py_INCREF( const_str_plain_key );
    const_tuple_str_plain_self_str_plain_data_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_data_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_data_tuple, 1, const_str_plain_data ); Py_INCREF( const_str_plain_data );
    const_tuple_str_plain_self_str_plain_port_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_port_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_port_tuple, 1, const_str_plain_port ); Py_INCREF( const_str_plain_port );
    const_bytearray_72cdf64f605ef12d57287fc4b61c2b5e = UNSTREAM_BYTEARRAY( &constant_bin[ 0 ], 0 );
    const_str_digest_06425a8e1b9d5eab562978eb6eacf777 = UNSTREAM_STRING( &constant_bin[ 18483 ], 40, 0 );
    const_str_digest_07b1711e38859082a6702459b5aea4e1 = UNSTREAM_STRING( &constant_bin[ 18523 ], 97, 0 );
    const_str_digest_088e326eed737fbd2d5feedf060c96ff = UNSTREAM_STRING( &constant_bin[ 18620 ], 21, 0 );
    const_str_digest_09388aafcb6adb40da642c8223c8e7c5 = UNSTREAM_STRING( &constant_bin[ 2043 ], 66, 0 );
    const_str_digest_094a5755decb0ff88251d419e9b9deb6 = UNSTREAM_STRING( &constant_bin[ 18641 ], 50, 0 );
    const_str_digest_145bf772d86c3cb38f291d317430df01 = UNSTREAM_STRING( &constant_bin[ 18691 ], 39, 0 );
    const_str_digest_14aa7bed476b499178dd8a4fa54d666e = UNSTREAM_STRING( &constant_bin[ 18730 ], 115, 0 );
    const_str_digest_1d3403f47e70d0d3c7366e99c0db7fa8 = UNSTREAM_STRING( &constant_bin[ 18845 ], 41, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING( &constant_bin[ 4202 ], 2, 0 );
    const_str_digest_2b96e25c8d393fdf065d358454fdf25c = UNSTREAM_STRING( &constant_bin[ 18886 ], 45, 0 );
    const_str_digest_33be1aa9452ea1a35db7fc513fc42137 = UNSTREAM_STRING( &constant_bin[ 18931 ], 18, 0 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING( &constant_bin[ 10563 ], 7, 0 );
    const_str_digest_464621b44ad0d4884db68a925fcb5c8f = UNSTREAM_STRING( &constant_bin[ 18949 ], 17, 0 );
    const_str_digest_47be6feae340d11ceea1b2be1116c946 = UNSTREAM_STRING( &constant_bin[ 18966 ], 44, 0 );
    const_str_digest_4b91cca6339a9a892cf0e30d6bd1bdfc = UNSTREAM_STRING( &constant_bin[ 19010 ], 120, 0 );
    const_str_digest_54cde0cd7a92974ff918f0defbd1eeb9 = UNSTREAM_STRING( &constant_bin[ 19130 ], 41, 0 );
    const_str_digest_57027c3185c735e629ff3e28a5a985c8 = UNSTREAM_STRING( &constant_bin[ 19171 ], 115, 0 );
    const_str_digest_58961c73026e70b23b08cf381b49e04e = UNSTREAM_STRING( &constant_bin[ 19286 ], 15, 0 );
    const_str_digest_59d8c08c8b321dd488f0cfd9cc30b9cf = UNSTREAM_STRING( &constant_bin[ 19301 ], 45, 0 );
    const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1 = UNSTREAM_STRING( &constant_bin[ 19346 ], 12, 0 );
    const_str_digest_66c5c36b8185e52d7e7b19bd4f1801a9 = UNSTREAM_STRING( &constant_bin[ 19358 ], 98, 0 );
    const_str_digest_67381b97568fd04864d7225afb09d3b9 = UNSTREAM_STRING( &constant_bin[ 19456 ], 209, 0 );
    const_str_digest_67e30ad9cc029aa9b34457de3a368897 = UNSTREAM_STRING( &constant_bin[ 19665 ], 57, 0 );
    const_str_digest_72db89f2656c7536ad3ca9676d132571 = UNSTREAM_STRING( &constant_bin[ 19722 ], 62, 0 );
    const_str_digest_754a48779fa33a021f9b94595a1c7603 = UNSTREAM_STRING( &constant_bin[ 19784 ], 18, 0 );
    const_str_digest_7bb187c562694df4ba2daaaf74308c83 = UNSTREAM_STRING( &constant_bin[ 861 ], 9, 0 );
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING( &constant_bin[ 19802 ], 46, 0 );
    const_str_digest_9ba51f6bdeff944f83e458f9b58790b4 = UNSTREAM_STRING( &constant_bin[ 19848 ], 17, 0 );
    const_str_digest_a41f7446b10852b7fa7917c8946aa5e1 = UNSTREAM_STRING( &constant_bin[ 19865 ], 46, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING( &constant_bin[ 19911 ], 47, 0 );
    const_str_digest_bd2e98b142ff21c9f389c674d6946c9a = UNSTREAM_STRING( &constant_bin[ 19958 ], 57, 0 );
    const_str_digest_c987d57c872daa303d57e57028663dbb = UNSTREAM_STRING( &constant_bin[ 20015 ], 41, 0 );
    const_str_digest_ca3087f1fed5e9b894c48e0dbbd2f218 = UNSTREAM_STRING( &constant_bin[ 20056 ], 10, 0 );
    const_str_digest_ca5d450d1c32d53f6bfc010c234e26bd = UNSTREAM_STRING( &constant_bin[ 20066 ], 16, 0 );
    const_str_digest_cee0e65b93fa2a88bd408284fcdf4582 = UNSTREAM_STRING( &constant_bin[ 20082 ], 36, 0 );
    const_str_digest_faa07c45c026cd5370bf39ce65b9f2d8 = UNSTREAM_STRING( &constant_bin[ 20118 ], 41, 0 );
    const_tuple_str_plain_self_str_plain_enable_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_enable_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_enable_tuple, 1, const_str_plain_enable ); Py_INCREF( const_str_plain_enable );
    const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple = PyTuple_New( 17 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 0, const_int_pos_50 ); Py_INCREF( const_int_pos_50 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 1, const_int_pos_75 ); Py_INCREF( const_int_pos_75 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 2, const_int_pos_110 ); Py_INCREF( const_int_pos_110 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 3, const_int_pos_134 ); Py_INCREF( const_int_pos_134 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 4, const_int_pos_150 ); Py_INCREF( const_int_pos_150 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 5, const_int_pos_200 ); Py_INCREF( const_int_pos_200 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 6, const_int_pos_300 ); Py_INCREF( const_int_pos_300 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 7, const_int_pos_600 ); Py_INCREF( const_int_pos_600 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 8, const_int_pos_1200 ); Py_INCREF( const_int_pos_1200 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 9, const_int_pos_1800 ); Py_INCREF( const_int_pos_1800 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 10, const_int_pos_2400 ); Py_INCREF( const_int_pos_2400 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 11, const_int_pos_4800 ); Py_INCREF( const_int_pos_4800 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 12, const_int_pos_9600 ); Py_INCREF( const_int_pos_9600 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 13, const_int_pos_19200 ); Py_INCREF( const_int_pos_19200 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 14, const_int_pos_38400 ); Py_INCREF( const_int_pos_38400 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 15, const_int_pos_57600 ); Py_INCREF( const_int_pos_57600 );
    PyTuple_SET_ITEM( const_tuple_5aee5ca7adb77075f0cc1cb4927b0a43_tuple, 16, const_int_pos_115200 ); Py_INCREF( const_int_pos_115200 );
    const_tuple_str_plain_self_str_plain_duration_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_duration_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_duration_tuple, 1, const_str_plain_duration ); Py_INCREF( const_str_plain_duration );
    const_tuple_str_plain_self_str_plain_exclusive_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_exclusive_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_exclusive_tuple, 1, const_str_plain_exclusive ); Py_INCREF( const_str_plain_exclusive );
    const_tuple_str_plain_self_str_plain_rs485_settings_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_rs485_settings_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_rs485_settings_tuple, 1, const_str_plain_rs485_settings ); Py_INCREF( const_str_plain_rs485_settings );
    const_tuple_str_digest_088e326eed737fbd2d5feedf060c96ff_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_088e326eed737fbd2d5feedf060c96ff_tuple, 0, const_str_digest_088e326eed737fbd2d5feedf060c96ff ); Py_INCREF( const_str_digest_088e326eed737fbd2d5feedf060c96ff );
    const_tuple_str_digest_145bf772d86c3cb38f291d317430df01_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_145bf772d86c3cb38f291d317430df01_tuple, 0, const_str_digest_145bf772d86c3cb38f291d317430df01 ); Py_INCREF( const_str_digest_145bf772d86c3cb38f291d317430df01 );
    const_tuple_str_digest_a41f7446b10852b7fa7917c8946aa5e1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_a41f7446b10852b7fa7917c8946aa5e1_tuple, 0, const_str_digest_a41f7446b10852b7fa7917c8946aa5e1 ); Py_INCREF( const_str_digest_a41f7446b10852b7fa7917c8946aa5e1 );
    const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 1, const_str_plain_args ); Py_INCREF( const_str_plain_args );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_args_str_plain_kwargs_tuple, 2, const_str_plain_kwargs ); Py_INCREF( const_str_plain_kwargs );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_58961c73026e70b23b08cf381b49e04e
    );
#endif
}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
