function Hd = filter normalised
%FILTER NORMALISED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 11-Feb-2018 15:25:34

% Equiripple Differentiator filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N = 15;                    % Order
F = [0 0.4 0.6 1];         % Frequency Vector
A = [0 125.66370614 0 0];  % Amplitude Vector
W = [1 1];                 % Weight Vector

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, F, A, W, 'differentiator');
Hd = dfilt.dffir(b);

% [EOF]
