function Hd = filter2
%FILTER2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 11-Feb-2018 01:18:26

% Equiripple Differentiator filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

N = 30;                    % Order
F = [0 20 30 50];          % Frequency Vector
A = [0 125.66370614 0 0];  % Amplitude Vector
W = [1 1];                 % Weight Vector

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, F/(Fs/2), A, W, 'differentiator');
Hd = dfilt.dffir(b);

% [EOF]
