var searchData=
[
  ['scalarbinaryoptraits',['ScalarBinaryOpTraits',['../structEigen_1_1ScalarBinaryOpTraits.html',1,'Eigen']]],
  ['scaling',['Scaling',['../classScaling.html',1,'']]],
  ['select',['Select',['../classEigen_1_1Select.html',1,'Eigen']]],
  ['selfadjointeigensolver',['SelfAdjointEigenSolver',['../classEigen_1_1SelfAdjointEigenSolver.html',1,'Eigen']]],
  ['selfadjointview',['SelfAdjointView',['../classEigen_1_1SelfAdjointView.html',1,'Eigen']]],
  ['simplicialcholesky',['SimplicialCholesky',['../classEigen_1_1SimplicialCholesky.html',1,'Eigen']]],
  ['simplicialcholeskybase',['SimplicialCholeskyBase',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialldlt',['SimplicialLDLT',['../classEigen_1_1SimplicialLDLT.html',1,'Eigen']]],
  ['simplicialllt',['SimplicialLLT',['../classEigen_1_1SimplicialLLT.html',1,'Eigen']]],
  ['solve',['Solve',['../classEigen_1_1Solve.html',1,'Eigen']]],
  ['solverbase',['SolverBase',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e',['SolverBase&lt; FullPivLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20partialpivlu_3c_20_5fmatrixtype_20_3e_20_3e',['SolverBase&lt; PartialPivLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverstorage',['SolverStorage',['../structEigen_1_1SolverStorage.html',1,'Eigen']]],
  ['solvewithguess',['SolveWithGuess',['../classEigen_1_1SolveWithGuess.html',1,'Eigen']]],
  ['sparse',['Sparse',['../structEigen_1_1Sparse.html',1,'Eigen']]],
  ['sparsecompressedbase',['SparseCompressedBase',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseCompressedBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseCompressedBase&lt; SparseVector&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e',['SparseCompressedBase&lt; Transpose&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparselu',['SparseLU',['../classEigen_1_1SparseLU.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20readonlyaccessors_20_3e',['SparseMapBase&lt; Derived, ReadOnlyAccessors &gt;',['../classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20writeaccessors_20_3e',['SparseMapBase&lt; Derived, WriteAccessors &gt;',['../classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4.html',1,'Eigen']]],
  ['sparsematrix',['SparseMatrix',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_20_3e',['SparseMatrix&lt; Scalar &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20int_20_3e',['SparseMatrix&lt; Scalar, ColMajor, int &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20storageindex_20_3e',['SparseMatrix&lt; Scalar, ColMajor, StorageIndex &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_2c_20storageindex_20_3e',['SparseMatrix&lt; Scalar, RowMajor, StorageIndex &gt;',['../classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrixbase',['SparseMatrixBase',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, true &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20cwisebinaryop_3c_20binaryop_2c_20lhs_2c_20rhs_20_3e_20_3e',['SparseMatrixBase&lt; CwiseBinaryOp&lt; BinaryOp, Lhs, Rhs &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; SparseVector&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparseview_3c_20matrixtype_20_3e_20_3e',['SparseMatrixBase&lt; SparseView&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e',['SparseMatrixBase&lt; Transpose&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20triangularview_3c_20matrixtype_2c_20mode_20_3e_20_3e',['SparseMatrixBase&lt; TriangularView&lt; MatrixType, Mode &gt; &gt;',['../classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparseqr',['SparseQR',['../classEigen_1_1SparseQR.html',1,'Eigen']]],
  ['sparseselfadjointview',['SparseSelfAdjointView',['../classEigen_1_1SparseSelfAdjointView.html',1,'Eigen']]],
  ['sparsesolverbase',['SparseSolverBase',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20bicgstab_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; BiCGSTAB&lt; _MatrixType, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmoddecomposition_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodDecomposition&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsimplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSimplicialLDLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsimplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSimplicialLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsupernodalllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSupernodalLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20conjugategradient_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; ConjugateGradient&lt; _MatrixType, _UpLo, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletecholesky_3c_20scalar_2c_20_5fuplo_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; IncompleteCholesky&lt; Scalar, _UpLo, _OrderingType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletelut_3c_20_5fscalar_2c_20_5fstorageindex_20_3e_20_3e',['SparseSolverBase&lt; IncompleteLUT&lt; _Scalar, _StorageIndex &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20leastsquaresconjugategradient_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; LeastSquaresConjugateGradient&lt; _MatrixType, _Preconditioner &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisoldlt_3c_20matrixtype_2c_20options_20_3e_20_3e',['SparseSolverBase&lt; PardisoLDLT&lt; MatrixType, Options &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisollt_3c_20matrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PardisoLLT&lt; MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisolu_3c_20matrixtype_20_3e_20_3e',['SparseSolverBase&lt; PardisoLU&lt; MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PastixLDLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PastixLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixlu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; PastixLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparselu_3c_20_5fmatrixtype_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; SparseLU&lt; _MatrixType, _OrderingType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparseqr_3c_20_5fmatrixtype_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; SparseQR&lt; _MatrixType, _OrderingType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20spqr_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SPQR&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20superilu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SuperILU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SuperLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20umfpacklu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; UmfPackLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsevector',['SparseVector',['../classEigen_1_1SparseVector.html',1,'Eigen']]],
  ['sparseview',['SparseView',['../classEigen_1_1SparseView.html',1,'Eigen']]],
  ['spqr',['SPQR',['../classEigen_1_1SPQR.html',1,'Eigen']]],
  ['stride',['Stride',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e',['Stride&lt; 0, Value &gt;',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_20stridetype_3a_3aouterstrideatcompiletime_2c_20stridetype_3a_3ainnerstrideatcompiletime_20_3e',['Stride&lt; StrideType::OuterStrideAtCompileTime, StrideType::InnerStrideAtCompileTime &gt;',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_20value_2c_200_20_3e',['Stride&lt; Value, 0 &gt;',['../classEigen_1_1Stride.html',1,'Eigen']]],
  ['superilu',['SuperILU',['../classEigen_1_1SuperILU.html',1,'Eigen']]],
  ['superlu',['SuperLU',['../classEigen_1_1SuperLU.html',1,'Eigen']]],
  ['superlubase',['SuperLUBase',['../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superilu_3c_20_5fmatrixtype_20_3e_20_3e',['SuperLUBase&lt; _MatrixType, SuperILU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SuperLUBase&lt; _MatrixType, SuperLU&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['svdbase',['SVDBase',['../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20bdcsvd_3c_20_5fmatrixtype_20_3e_20_3e',['SVDBase&lt; BDCSVD&lt; _MatrixType &gt; &gt;',['../classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20jacobisvd_3c_20_5fmatrixtype_2c_20qrpreconditioner_20_3e_20_3e',['SVDBase&lt; JacobiSVD&lt; _MatrixType, QRPreconditioner &gt; &gt;',['../classEigen_1_1SVDBase.html',1,'Eigen']]]
];
