%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/feb2/acro_mode.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/02 13:00:13
clear all 
close all
%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/feb2/acro_mode.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: text (%s)
%   column15: text (%s)
%	column16: text (%s)
%   column17: text (%s)
%	column18: text (%s)
%   column19: text (%s)
%	column20: text (%s)
%   column21: text (%s)
%	column22: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
VarName2 = dataArray{:, 2};
VarName3 = dataArray{:, 3};
VarName4 = dataArray{:, 4};
VarName5 = dataArray{:, 5};
VarName6 = dataArray{:, 6};
VarName7 = dataArray{:, 7};
VarName8 = dataArray{:, 8};
VarName9 = dataArray{:, 9};
VarName10 = dataArray{:, 10};
VarName11 = dataArray{:, 11};
VarName12 = dataArray{:, 12};
VarName13 = dataArray{:, 13};
VarName14 = dataArray{:, 14};
VarName15 = dataArray{:, 15};
VarName16 = dataArray{:, 16};
VarName17 = dataArray{:, 17};
VarName18 = dataArray{:, 18};
VarName19 = dataArray{:, 19};
VarName20 = dataArray{:, 20};
VarName21 = dataArray{:, 21};
VarName22 = dataArray{:, 22};

time_ms = VarName1./1000;
pitch   = VarName2./1000;
pitch_rate   = VarName3./1000;
r_pitch_rate = VarName4./1000.*180./pi;
m3 = VarName8./1000;
m4 = VarName9./1000;
omega3 = VarName10./1000;
omega4 = VarName11./1000;

thrust3 = VarName12./1000;
thrust4 = VarName13./1000;

netThrust = VarName7./1000;

plot(time_ms,pitch_rate)
hold on;plot(time_ms,r_pitch_rate)

% figure
% plot(time_ms, m3)
% hold on
% plot(time_ms, m4)
% 
% figure
% plot(time_ms, thrust3)
% hold on
% plot(time_ms, thrust4)
% 
% figure
% plot(time_ms, omega3)
% hold on
% plot(time_ms, omega4)

% %% Moment comparison
% e = -(pitch_rate - r_pitch_rate);
% kp = 0.0838
% ki = 0.1031
% kd = 0.01586
% integral = 0;
% 
% for i = 1:(length(e)-1)
% Moment_exp(i) = (kp*e(i) + (e(i+1)-e(i))/0.05*kd + ki*integral)*pi/180;
% integral = integral + e(i)*0.05;
% end
% plot(time_ms(1:end-1), Moment_exp)
% hold on
% Moment_c = (thrust3 - thrust4)*0.2;
% plot(time_ms, Moment_c)
% %% thrust comparision
% figure
% plot(time_ms,netThrust)
% hold on
% plot(time_ms,2*(thrust3+thrust4))
% %% Specific pulse width
% u3 = 1.434e-6*omega3.^2 + 0.0003803*omega3 + 0.1045;
% u4 = 1.434e-6*omega4.^2 + 0.0003803*omega4 + 0.1045;
% figure
% plot(time_ms, u3)
% hold on
% plot(time_ms, u4)
% figure
% plot(time_ms,(m3-1000)/1000)
% hold on
% plot(time_ms,u3)
%% Angular velocity comparison

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;