%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/feb2/att_mode_ts_1.5.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/02 18:36:01
clear all
close all
% outer gain = 3
%float rate_pitch[6] = {0.0838,    0.01586,    0.1031, 1.0 , 1.0 , 25};

%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/feb2_stand_test/att_mode_ts_1.5.csv';
delimiter = ',';
startRow = 2;

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Exclude rows with non-numeric cells
I = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2); % Find rows with non-numeric cells
raw(I,:) = [];

%% Allocate imported array to column variable names
time = cell2mat(raw(:, 1));
pitch = cell2mat(raw(:, 2));
angularvel = cell2mat(raw(:, 3));
r_pitch_rate = cell2mat(raw(:, 4));
r_pitch = cell2mat(raw(:, 5));
radio3 = cell2mat(raw(:, 6));
netThrust = cell2mat(raw(:, 7));
m3 = cell2mat(raw(:, 8));
m4 = cell2mat(raw(:, 9));
speed3 = cell2mat(raw(:, 10));
speed4 = cell2mat(raw(:, 11));
t3 = cell2mat(raw(:, 12));
t4 = cell2mat(raw(:, 13));

time = time/1000;
pitch = pitch/1000;
angularvel = angularvel/1000;
r_pitch = r_pitch/1000;
r_pitch_rate = r_pitch_rate/1000*180/pi;
radio3 = (radio3-1000)/1000;
netThrust = netThrust/1000;
m3 = m3/1000;
m4 = m4/1000;

plot(time,r_pitch)
hold on
plot(time,pitch)

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp I J K;