%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/june30/bench test of fcb.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/30 18:34:54

%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/june30/bench test of fcb.csv';
delimiter = ' ';

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Exclude rows with non-numeric cells
I = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2); % Find rows with non-numeric cells
raw(I,:) = [];

%% Create output variable
flightLog = table;
flightLog.time = cell2mat(raw(:, 1));
flightLog.pitch = cell2mat(raw(:, 2));
flightLog.roll = cell2mat(raw(:, 3));
flightLog.yaw = cell2mat(raw(:, 4));
flightLog.gx = cell2mat(raw(:, 5));
flightLog.gy = cell2mat(raw(:, 6));
flightLog.gz = cell2mat(raw(:, 7));
flightLog.m1 = cell2mat(raw(:, 8));
flightLog.m2 = cell2mat(raw(:, 9));
flightLog.m3 = cell2mat(raw(:, 10));
flightLog.m4 = cell2mat(raw(:, 11));
flightLog.rx1 = cell2mat(raw(:, 12));
flightLog.rx2 = cell2mat(raw(:, 13));
flightLog.rx3 = cell2mat(raw(:, 14));
flightLog.rx4 = cell2mat(raw(:, 15));
flightLog.rx5 = cell2mat(raw(:, 16));
flightLog.rx6 = cell2mat(raw(:, 17));
flightLog.VarName18 = cell2mat(raw(:, 18));
flightLog.VarName19 = cell2mat(raw(:, 19));
flightLog.VarName20 = cell2mat(raw(:, 20));
flightLog.VarName21 = cell2mat(raw(:, 21));
flightLog.VarName22 = cell2mat(raw(:, 22));
flightLog.VarName23 = cell2mat(raw(:, 23));

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp I J K;