%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/july7/testRun_withoutProp115200baud.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/07/07 17:07:17

%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/july7/testRun_withoutProp115200baud.csv';
delimiter = ' ';

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
time = cell2mat(raw(:, 1));
pitch = cell2mat(raw(:, 2));
roll = cell2mat(raw(:, 3));
ax = cell2mat(raw(:, 4));
ay = cell2mat(raw(:, 5));
az = cell2mat(raw(:, 6));
gx = cell2mat(raw(:, 7));
gy = cell2mat(raw(:, 8));
gz = cell2mat(raw(:, 9));
m1 = cell2mat(raw(:, 10));
m2 = cell2mat(raw(:, 11));
m3 = cell2mat(raw(:, 12));
m4 = cell2mat(raw(:, 13));
u1 = cell2mat(raw(:, 14));
u2 = cell2mat(raw(:, 15));
u3 = cell2mat(raw(:, 16));
u4 = cell2mat(raw(:, 17));
VarName18 = cell2mat(raw(:, 18));
VarName19 = cell2mat(raw(:, 19));
VarName20 = cell2mat(raw(:, 20));
VarName21 = cell2mat(raw(:, 21));
VarName22 = cell2mat(raw(:, 22));
VarName23 = cell2mat(raw(:, 23));
VarName24 = cell2mat(raw(:, 24));
VarName25 = cell2mat(raw(:, 25));
VarName26 = cell2mat(raw(:, 26));
VarName27 = cell2mat(raw(:, 27));
VarName28 = cell2mat(raw(:, 28));
VarName29 = cell2mat(raw(:, 29));
VarName30 = cell2mat(raw(:, 30));
VarName31 = cell2mat(raw(:, 31));
VarName32 = cell2mat(raw(:, 32));
VarName33 = cell2mat(raw(:, 33));


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp R;