%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/sep18_ctc_altitudeCF/alt hand test.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/18 16:41:15

%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/sep18_ctc_altitudeCF/alt hand test.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time_ms = dataArray{:, 1};
imu_roll1 = dataArray{:, 2};
imu_pitch1 = dataArray{:, 3};
ax1 = dataArray{:, 4};
ay1 = dataArray{:, 5};
az1 = dataArray{:, 6};
gx1 = dataArray{:, 7};
gy1 = dataArray{:, 8};
gz1 = dataArray{:, 9};
Setpoint_rollRate1 = dataArray{:, 10};
set_pitchRate1 = dataArray{:, 11};
Setpoint_yawRate1 = dataArray{:, 12};
Setpoint_roll1 = dataArray{:, 13};
Setpoint_pitch1 = dataArray{:, 14};
radio_1 = dataArray{:, 15};
height1 = dataArray{:, 16};
heightRate1 = dataArray{:, 17};
Setpoint_heightRate = dataArray{:, 18};
height_PID_output = dataArray{:, 19};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;