; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:nucleo_f446re]
; [enc:release]
platform    = ststm32
board       = nucleo_f446re
framework   = mbed
build_flags = -Wall -std=gnu++11  ;suport for c++11
build_unflags = -std=gnu++98 ;remove the unnecessary c++98 support
upload_protocol = stlink
targets = release

; build_unflags =
; lib_deps =
  ; # Using a library name
  ; MODSERIAL_ID2542
  ; build_flags =  -std=gnu++14 ;support for c++11
  ; build_unflags = -Wall -std=gnu++98 -std=gnu++11
