%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/august22_ctc_LIionPack/tooAggressiveControl_matlab_tuned.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/22 19:07:25
clear
%% Initialize variables.
filename = '/home/manoj/gits/Flight-Control-Board/FCBcode/quadcopter/FCBquad/FCB_V_2_0/flight_logs/august22_ctc_LIionPack/tooAggressiveControl_matlab_tuned.csv';
delimiter = '\t';
startRow = 2;
ColumnNo = 15
startFlight = 400
endFlight = 500
%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray1 = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.
%% Scaling
% dataArray1 = dataArray{startFlight:endFlight, :};
for i = 1:ColumnNo
dataArray1{:,i} = dataArray1{:, i} / 1000;
end
%% Allocate imported array to column variable names
time_ms = dataArray1{:, 1};
imu_roll = dataArray1{:, 2};
imu_pitch = dataArray1{:, 3};
ax = dataArray1{:, 4};
ay = dataArray1{:, 5};
az = dataArray1{:, 6};
gx = dataArray1{:, 7};
gy = dataArray1{:, 8};
gz = dataArray1{:, 9};
Setpoint_rollRate = dataArray1{:, 10};
set_pitchRate = dataArray1{:, 11};
Setpoint_yawRate = dataArray1{:, 12};
Setpoint_roll = dataArray1{:, 13};
Setpoint_pitch = dataArray1{:, 14};
radio_3 = dataArray1{:, 15};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID ans dataArray;